language: php
php:
  - 7.1

services:
  - docker
  - docker-compose

install:
  - docker-compose build

script:
  - docker-compose up -d
  - docker ps | grep -q wordpress
  - curl localhost:8000
  - docker-compose stop
