language: php
php:
  - 7.1

services:
  - docker
  - docker-compose

before_script:
  - docker-compose up --build -d

script:
  - docker ps | grep -q wordpress
  - bash -c "for i in {1..30}; do curl localhost:8000 >/dev/null && break || sleep 5; done"
  - curl localhost:8000

after_script:
  - docker-compose logs
  - docker-compose down
