language: php
php:
  - 7.1

services:
  - docker
  - docker-compose

install:
  - docker-compose build

before_script:
  - docker-compose up -d

script:
  - docker ps | grep -q wordpress
  - bash -c "for i in {1..30}; do curl localhost:8000 >/dev/null 2>&1 && break || sleep 5; done"
  - curl localhost:8000 | grep -q "<title>My Awesome Blog"

after_script:
  - docker-compose logs
  - docker-compose down
