version: '2'

services:

  wordpress:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: musikcorps:latest
    links:
      - database:mysql
    ports:
      - 8000:80

  database:
    image: mariadb
    env_file: config/docker.env

