version: '2'

services:

  wordpress:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: wordpress-uberspace:latest
    links:
      - database:mysql
    ports:
      - 8000:80

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: a
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: changeme1

